### ISSUE TITLE
RxFirebaseStorage.putFile onError but no error

### ISSUE THREAD

**Issue by rcheze** [nmoskalenko/rxFirebase#15]
I got an error while using RxFirebaseStorage.putFile(storageReference, uri) 
on version 0.0.14 of this lib and
using 'com.google.firebase:firebase-storage:9.4.0'

onError: 
  java.lang.UnsupportedOperationException: addOnCompleteListener is not implemented
         at com.google.android.gms.tasks.Task.addOnCompleteListener(Unknown Source)
         at com.kelvinapps.rxfirebase.RxHandler.assignOnTask(RxHandler.java:27)
         at com.kelvinapps.rxfirebase.RxFirebaseStorage$10.call(RxFirebaseStorage.java:127)
         at com.kelvinapps.rxfirebase.RxFirebaseStorage$10.call(RxFirebaseStorage.java:124)
         at rx.Observable.subscribe(Observable.java:10246)
         at rx.Observable.subscribe(Observable.java:10213)

Even though the image was correctly uploaded.

**Comment by nmoskalenko** [comment]
fixed in ver 0.15
