### ISSUE TITLE
linkWithCredential doesn't seem to work

### ISSUE THREAD

**Issue by tonnyavery** [nmoskalenko/rxFirebase#21]
After using RxFirebaseUser.linkWithCredetial for facebook token Firebase Console in the web doesn't show a user with facebook connected.
Second attempt to link already linked user doesn't result in an exception that is know to be thrown by firebase in that case

**Comment by tonnyavery** [comment]
Linked fine. Couldn't reproduce, weird

**Comment by tonnyavery** [comment]
I get this error:
```
W/System.err: com.google.firebase.auth.FirebaseAuthUserCollisionException: This credential is already associated with a different user account.
W/System.err:     at com.google.android.gms.internal.zzahe.zzfc(Unknown Source)
W/System.err:     at com.google.android.gms.internal.zzahb$zzg.zza(Unknown Source)
W/System.err:     at com.google.android.gms.internal.zzahm.zzfd(Unknown Source)
W/System.err:     at com.google.android.gms.internal.zzahm$zza.onFailure(Unknown Source)
W/System.err:     at com.google.android.gms.internal.zzahh$zza.onTransact(Unknown Source)
W/System.err:     at android.os.Binder.execTransact(Binder.java:453)
```
